### ISSUE TITLE
关于过滤补充规则

### ISSUE THREAD

**Issue by ghost** [loveqqzj/AdGuard#1]
你好:

关于 mobile.txt 文件可以请你添加这些规则吗?

doubleclick.net^
trvdp.com^

thanks.

@loveqqzj

**Comment by loveqqzj** [comment]
你是要把这两个网址屏蔽掉？

**Comment by loveqqzj** [comment]
> 你好:
> 
> 关于 mobile.txt 文件可以请你添加这些规则吗?
> 
> doubleclick.net^
> trvdp.com^
> 
> thanks.
> 
> @loveqqzj
你是要把这两个网址屏蔽掉？
